spring:
  # database
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis
mybatis:
  mapper-locations: mybatis/mapper/**/*.xml
  config-location: classpath:/mybatis/mybatis-config.xml
